frontend/src/App.tsx

- Solve #8 
- Web에서도 모바일과 비슷한 화면을 나타냄, 배경 회색처리

feat: Set base container

---

frontend/package.json
frontend/src/App.tsx
frontend/src/components/header.tsx
frontend/src/components/sidebar.tsx
frontend/src/pages/home.tsx
frontend/yarn.lock

**이슈번호**
resolved: #16 
**작업내용**
> 사이드바 크기 수정

[FIX] 모바일 화면에 따른 사이드바 크기 조정

---

frontend/src/components/header.tsx
frontend/src/pages/home.tsx

#20 에서 헤더를 먼저 구현하여 pr합니다!
WireFrame에서는 알림/검색기능이 있었는데 가장 기본기능 먼저 구현하고자 제외했고 임시로 로그인 버튼을 넣어놓았습니다

feat: Add header component

---

frontend/.gitignore
frontend/src/pages/login.tsx

**이슈번호**
resolved: #18 
**작업내용**
> 프론트엔드 구글 로그인 추가

[FEAT] 구글 로그인을 통해 사용자 정보를 콘솔로 출력

---

frontend/package-lock.json
frontend/src/components/header.tsx
frontend/src/pages/login.tsx
frontend/src/pages/oauth2-redirect.tsx
frontend/src/routers/common-router.tsx

**이슈번호**
resolved: #22 
**작업내용**
> 구글 로그인 버튼 삭제
> 소셜 로그인 버튼 통일(백엔드로 연결)
> 헤더에서 연결되는 사이드바 전체에서 밖으로 나가는 onClick이 적용되던 문제 수정

[FEAT] 프론트엔드 소셜 로그인

---

frontend/.eslintrc.js
frontend/.prettierrc
frontend/package.json
frontend/yarn.lock

**이슈번호**
resolved: #25 
**작업내용**
> prettier, eslint 설정파일 적용

[DOCS] Prettier, Eslint 설정파일 적용

---

frontend/package-lock.json
frontend/package.json

[DOCS] Update package.json

---

frontend/package-lock.json
frontend/src/pages/goguma.tsx
frontend/src/routers/common-router.tsx

이슈번호
resolved: #31 
작업내용
> 작성된 글 확인하는 페이지 추가
> 글 확인용 Fake Data

[FEAT] 작성된 글을 확인하는 고구마 페이지

---

frontend/.eslintrc.js
frontend/src/App.tsx
frontend/src/components/sidebar.tsx
frontend/src/index.tsx
frontend/src/pages/404.tsx
frontend/src/pages/goguma.tsx
frontend/src/pages/home.tsx
frontend/src/pages/login.tsx
frontend/src/pages/oauth2-redirect.tsx
frontend/src/reportWebVitals.ts
frontend/src/routers/common-router.tsx

**이슈번호**
resolved: x
작업내용
> eslint error fix

[FIX] Eslint 적용으로 error로 표시되던 부분 수정

---

frontend/.eslintrc.js

```
Delete `␍` eslint (prettier/prettier)
```
위 오류가 발생해서 [이 글](https://noogoonaa.tistory.com/62) 보고 수정했는데 확인 한번 부탁드려욜~

[FIX] Add prettier rule

---

frontend/src/components/content-header.tsx
frontend/src/components/main-header.tsx
frontend/src/pages/ask.tsx

- Resolve part of #56 
- 업데이트된 content header 적용
- 제목 작성 페이지 추가 (active여부 적용X)

[FEAT] Update ask page

---

frontend/src/components/display-time.tsx
frontend/src/components/sidebar.tsx
frontend/src/pages/notifications.tsx
frontend/src/routers/common-router.tsx

이슈번호
resolved: #62 
작업내용
> 알림 페이지 추가

[FEAT] 알림 페이지 구현

---

frontend/src/pages/ask.tsx

- Resolve part of #56 
- 질문 내용 작성 페이지에 line이 있는 Textarea를 추가했습니다
- 높이 / 임의 마진을 이렇게 픽스하고싶지는 않았지만ㅠ,ㅠ 일단은 ui 구현을 위해 고정합니다..

feat: Add textarea lines at ask page

---

frontend/src/App.tsx
frontend/src/components/sidebar.tsx
frontend/src/pages/goguma-basket.tsx
frontend/src/pages/notifications.tsx
frontend/src/pages/search.tsx

**이슈번호**
resolved: #67 
**작업내용**
> 페이지 사이즈 변경
> 작성된 ui가 최대한 틀어지지 않게 했는데 혹시 이상한 부분이 있을수도 있어요...

[FEAT]보이는 페이지 사이즈 변경

---

frontend/src/pages/ask.tsx

- Resolve part of #56 
- 선택지 추가 텍스트 ui를 업데이트했습니다~
- 네이밍 리팩토링도 조금 햇습니다

[FEAT] Add '선택지 추가' text ui

---

backend/selection/src/main/java/com/selection/domain/article/Article.java
backend/selection/src/main/java/com/selection/domain/question/Question.java
backend/selection/src/main/java/com/selection/domain/tag/Tag.java
backend/selection/src/test/java/com/selection/domain/article/ArticleTest.java
backend/selection/src/test/java/com/selection/domain/question/QuestionTest.java
backend/selection/src/test/java/com/selection/domain/tag/TagTest.java
backend/selection/src/test/resources/application-local.yaml

**이슈번호**
#71 
**작업내용**
1. Article, Question, Tag 단위테스트 수정
2. Article, Question, Tag 생성자 validation 추가

fix: 테스트 깨지는 문제 해결

---

frontend/src/App.tsx
frontend/src/routers/common-router.tsx
frontend/src/styles/FontStyles.css

이슈번호
resolved: #74 
작업내용
유저유무에따른 라우터 조정, 유저를 불러오는동안 로딩

[FEAT] 유저 소셜 로그인 기능 라우터

---

backend/selection/build.gradle
backend/selection/src/main/java/com/selection/config/SecurityConfig.java
backend/selection/src/main/java/com/selection/config/SwaggerConfig.java
backend/selection/src/main/java/com/selection/controller/ArticleController.java
backend/selection/src/main/java/com/selection/controller/GogumaController.java
backend/selection/src/main/java/com/selection/controller/UserController.java
backend/selection/src/main/java/com/selection/dto/article/ArticleRequest.java
backend/selection/src/main/java/com/selection/dto/article/ArticleResponse.java
backend/selection/src/main/java/com/selection/dto/choice/ChoiceRequest.java
backend/selection/src/main/java/com/selection/dto/choice/ChoiceResponse.java
backend/selection/src/main/java/com/selection/dto/goguma/GogumaRequest.java
backend/selection/src/main/java/com/selection/dto/goguma/GogumaResponse.java
backend/selection/src/main/java/com/selection/security/user/UserService.java
backend/selection/src/main/java/com/selection/service/user/UserService.java

**Subject**
[FEAT] Swagger 도입
**Detail**
- Swagger 도입
- 연동부분 오류있어 잠시 보류 ( 프론트 상의 후 다시 작성)
-  UserService 패키지 이동

[FEAT] Swagger 도입

---

backend/selection/src/main/java/com/selection/controller/UserController.java

fix: 소셜 로그인 연동 부분 복구

---

backend/selection/src/main/java/com/selection/controller/OAuth2Controller.java
backend/selection/src/main/java/com/selection/controller/UserController.java

fix: token 발급 경로수정, OAuth2 컨트롤러 분리

---

backend/selection/.gitignore
backend/selection/build.gradle
backend/selection/src/main/java/com/selection/SelectionApplication.java
backend/selection/src/main/resources/application.yaml

배포 설정
- EC2 RDS 설정
- RDS 연결 설정
- 배포 스크립트 일부 수정

feat: 배포 설정

---

backend/selection/build.gradle
backend/selection/src/main/resources/logback-spring.xml

[FEAT]Sentry 설정

---

frontend/src/constants.ts

제가 작업했던 부분이 아니라서 수정한 내용이 맞는지 확인 부탁드립니다~~

[FIX] backend url port number

---

frontend/src/pages/goguma-info.tsx
frontend/src/pages/my-page.tsx
frontend/src/routers/common-router.tsx

**이슈번호**
resolved: #100 
**작업내용**
> 고구마는.. 페이지 구현

[FEAT] 고구마는.. 페이지

---

frontend/src/pages/login.tsx

**이슈번호**
resolved: #107 
**작업내용**
로그인 페이지 수정
> 카카오 로그인 추가

[FEAT] 로그인 페이지 UI 수정

---

backend/selection/build.gradle

**Where**
Swagger Annoations, Swagger Models
**Bug detail**
Swagger의 Annotations, Swagger Models의 고전적인 문제
**Fix plan**
Swagger Annotations, Swagger Models의 Verion Downgrade

[FIX]Swagger Annoations, Swagger Models Version Downgrade

---

backend/selection/build.gradle

Swagger Annotations, Swagger Models 구버전 Import

[FIX]Swagger Annoations, Swagger Models Import

---

backend/selection/src/main/java/com/selection/controller/ArticleController.java
backend/selection/src/main/java/com/selection/controller/GogumaController.java
backend/selection/src/main/java/com/selection/controller/UserController.java
backend/selection/src/main/java/com/selection/domain/article/Choices.java
backend/selection/src/main/java/com/selection/domain/article/GogumaService.java
backend/selection/src/main/java/com/selection/domain/notification/Notification.java
backend/selection/src/main/java/com/selection/domain/notification/NotificationRepository.java
backend/selection/src/main/java/com/selection/domain/notification/NotificationService.java
backend/selection/src/main/java/com/selection/domain/user/User.java
backend/selection/src/main/java/com/selection/domain/user/UserRepository.java
backend/selection/src/main/java/com/selection/domain/user/UserService.java
backend/selection/src/main/java/com/selection/dto/goguma/GogumaResponse.java
backend/selection/src/main/java/com/selection/dto/notification/NotificationResponse.java

**Subject**
알림 API 작성
**Detail**
- 알림 조회 API
- 알림 읽음 API
- 알림 삭제 API

feat: 알림 전송 로직, 알림 조회 API 작성

---

backend/selection/src/test/java/com/selection/controller/GogumaControllerTest.java

**Where**
고구마 등록 API 테스트 코드 ( GogumaControllerTest.java )
**Bug detail**
- 고구마 등록 과정에 알림 전송 기능이 추가되어 테스트간의 의존성이 생김
**Fix plan**
- Deprecated

[BUG]고구마 등록 테스트 코드 의존성 이슈, 보류

---

frontend/src/components/goguma-card.tsx
frontend/src/components/sidebar.tsx
frontend/src/pages/goguma-list-honor.tsx
frontend/src/pages/goguma-list-popular.tsx
frontend/src/pages/goguma-list-resent.tsx

**이슈번호**
resolved: #123 
**작업내용**
> 게시글 리스트 백엔드 API 적용

[FEAT] 인기글 최신글 명예글 API 적용

---

frontend/src/pages/notifications.tsx
frontend/src/routers/common-router.tsx

이슈번호
resolved: #126 
작업내용
api 적용한 알림 페이지 구현(login token 적용 후 수정 예정)

[FEAT] 알림 페이지 재추가

---

frontend/src/components/sidebar.tsx

이슈번호
resolved: #130 
작업내용
사이드바에 notification 링크 버튼 추가

[FEAT] 사이드바 notification 링크 버튼

---

frontend/src/interface/IData.tsx
frontend/src/pages/ask-success.tsx
frontend/src/pages/ask.tsx
frontend/src/pages/home.tsx

지금까지의 작업분을 PR합니다..
- 메인페이지 API 적용
- 등록완료페이지 API 적용
- 등록완료페이지 UI 수정
- 메인페이지 UI 수정

[FEAT] Update UI, Apply API

---

frontend/src/components/goguma-card.tsx
frontend/src/components/sidebar.tsx
frontend/src/pages/goguma-list-me.tsx
frontend/src/pages/my-page.tsx
frontend/src/routers/common-router.tsx

이슈번호
resolved: #132 
작업내용
api 적용한 내가 쓴 글 페이지

[FEAT] 내가 쓴 글 리스트 페이지 API 적용

---

frontend/src/components/sidebar.tsx
frontend/src/pages/goguma-list-honor.tsx
frontend/src/pages/goguma-list-me.tsx
frontend/src/pages/goguma-list-popular.tsx

이슈번호
resolved: #137 
작업내용
고구마 리스트 페이지 링크 기능 추가

[FEAT] 고구마 리스트 페이지 링크 기능

---

backend/selection/src/main/java/com/selection/domain/article/ArticleRepository.java
backend/selection/src/main/java/com/selection/dto/article/ArticleSummaryProjection.java
backend/selection/src/main/java/com/selection/dto/article/ArticleSummaryResponse.java

**Subject**
- 인기글 API 필드 변경
**Detail**
- userId -> nickname 으로 변경

[REFACTOR]인기글 API 필드 변경

---

backend/selection/src/main/java/com/selection/dto/article/ArticleResponse.java
backend/selection/src/main/java/com/selection/dto/article/ArticleSummaryResponse.java

**Subject**
- 게시글 조회 내용 짤림 이슈 수정
**Detail**
- 게시글 조회 내용 짤림 발생

[REFACTOR]게시글 조회 내용 짤림 이슈 수정

---

frontend/src/pages/goguma.tsx
frontend/src/routers/common-router.tsx

이슈번호
resolved: #144 
작업내용
고구마 게시글 페이지 api 연동

[FEAT] 게시글 조회 수정 삭제 api 연동

---

frontend/src/components/sidebar.tsx
frontend/src/pages/goguma-list-honor.tsx
frontend/src/pages/goguma-list-me.tsx
frontend/src/pages/goguma-list-popular.tsx
frontend/src/pages/goguma-list-resent.tsx
frontend/src/pages/notifications.tsx
frontend/src/styles/img/icon_alarm.svg

**이슈번호**
resolved: #148 
**내용**
- 고구마 리스트에서 적용되던 data 변수 수정(author > nickname)

[REFACTOR] 고구마 리스트 작성자 변수 수정 #148

---

backend/selection/src/main/java/com/selection/advice/ExceptionAdvice.java
backend/selection/src/main/java/com/selection/controller/GogumaController.java
backend/selection/src/main/java/com/selection/domain/article/Goguma.java
backend/selection/src/main/java/com/selection/domain/article/GogumaRepository.java
backend/selection/src/main/java/com/selection/domain/article/GogumaService.java
backend/selection/src/main/java/com/selection/domain/article/GogumaType.java
backend/selection/src/main/java/com/selection/domain/article/Gogumas.java
backend/selection/src/main/java/com/selection/domain/notification/Notification.java
backend/selection/src/main/java/com/selection/domain/notification/NotificationService.java
backend/selection/src/main/java/com/selection/dto/ErrorResponse.java
backend/selection/src/main/java/com/selection/dto/goguma/GogumaRequest.java
backend/selection/src/main/java/com/selection/dto/goguma/GogumaSummaryResponse.java
backend/selection/src/main/java/com/selection/dto/goguma/HotGogumaType.java
backend/selection/src/main/java/com/selection/dto/notification/NotificationResponse.java

**Subject**
고구마 관련 기능
**Detail**
- 고구마 쪽지 조회시 메세지가 존재하는지 여부 필드, 작성자가 읽었는지 읽음 표시
- 고구마 바구니 조회 API 작성
- 고구마 작성시 고구마 id 반환

[FEAT] 고구마 관련 기능

---

frontend/src/components/sidebar.tsx
frontend/src/pages/goguma-gogumas.tsx
frontend/src/pages/my-page.tsx
frontend/src/pages/notifications.tsx
frontend/src/routers/common-router.tsx

이슈번호
resolved: #157 
작업내용
getUser 에서 error 처리를 try catch 로 변경

[REFACTOR] getUser error 시 토큰이 삭제되는 부분 수정

---

frontend/src/components/emoji.tsx
frontend/src/pages/goguma-gogumas.tsx
frontend/src/pages/goguma-list-honor.tsx
frontend/src/pages/goguma-list-me.tsx
frontend/src/pages/goguma-list-popular.tsx
frontend/src/pages/goguma.tsx

이슈번호
resolved: #159 
작업내용
고구마 쪽지 보내기 기능 api 연동

[FEAT] 고구마 쪽지 보내기 기능

---

backend/selection/src/main/java/com/selection/advice/ExceptionAdvice.java
backend/selection/src/main/java/com/selection/controller/OAuth2Controller.java
backend/selection/src/main/java/com/selection/domain/article/GogumaType.java
backend/selection/src/main/java/com/selection/dto/article/ArticleResponse.java
backend/selection/src/main/java/com/selection/dto/article/ArticleSummaryResponse.java
backend/selection/src/main/java/com/selection/dto/choice/ChoiceResponse.java
backend/selection/src/main/java/com/selection/dto/goguma/GogumaResponse.java
backend/selection/src/main/java/com/selection/dto/goguma/GogumaSummaryResponse.java
backend/selection/src/main/java/com/selection/dto/notification/NotificationResponse.java
backend/selection/src/main/resources/application-local.yaml

**Subject**
- 일부 필드명 변경 및 에러 수정
**Detail**
- GogumaType의 "SUPRISED" -> "SURPRISED" 로 변경
- boolean type variable의 "is" prefix가 무시되던 문제 수정
- Enum 타입이 대소문자 혼합일 경우 인식되지 않던 문제
- Swagger의 Resposne DTO field Description 수정

[REFACTOR] 일부 필드명 변경 및 에러 수정

---

frontend/src/components/main-header.tsx
frontend/src/pages/ask-success.tsx
frontend/src/pages/home.tsx
frontend/src/routers/common-router.tsx

쉽게 수정된 부분 먼저 피알합니다~
- Change main header font weight to Regular
- Change ask success page route
- Edit card margin on main page

[FIX] 0225

---

frontend/src/components/content-header.tsx
frontend/src/components/emoji.tsx
frontend/src/components/goguma-card.tsx
frontend/src/components/sidebar.tsx
frontend/src/pages/goguma-basket.tsx
frontend/src/pages/goguma-gogumas.tsx
frontend/src/pages/goguma-info.tsx
frontend/src/pages/goguma-list-honor.tsx
frontend/src/pages/goguma-list-me.tsx
frontend/src/pages/goguma-list-popular.tsx
frontend/src/pages/goguma-list-resent.tsx
frontend/src/pages/goguma.tsx
frontend/src/pages/login.tsx
frontend/src/pages/my-page.tsx
frontend/src/pages/notifications.tsx

이슈번호
resolved: #166 
작업내용
- 게시글 리스트
- 게시글보기
- 고구마 쪽지
- 고구마 바구니
- 마이페이지
- 사이드바
- 알림페이지

[REFACTOR] 프론트엔드 Css 작업

---

frontend/src/pages/ask.tsx
frontend/src/pages/home.tsx

소소한 수정
fix: Ask page text counter UI
fix: Set font-weight regular to Ask page desc
fix: Set font weight at main page
fix: Remove word break
fix: Set font weight

[FIX] 02 25 추가

---

frontend/src/pages/ask.tsx

- Ask page에서 선택지 선택 및 입력 기능
동작을 최우선시 하다보니 생각없이 코드를 만들었네요😭
우선 해야하는 TODO
- Ask page post api
- Ask page 헤더

[FEAT] User can select ChoiceBox and input text

---

backend/selection/src/main/java/com/selection/domain/notification/NotificationService.java
backend/selection/src/main/java/com/selection/dto/notification/NotificationResponse.java

**Subject**
알림 API에 게시글 번호 추가
**Detail**
- 알림 API Response에 article_id field 추가

[FEAT] 알림 API에 게시글 번호 추가

---

backend/selection/src/main/java/com/selection/controller/UserController.java
backend/selection/src/main/java/com/selection/domain/user/User.java
backend/selection/src/main/java/com/selection/domain/user/UserService.java
backend/selection/src/main/java/com/selection/dto/user/ProfileRequest.java

**Subject**
- 닉네임 변경 API
**Detail**
- 유저의 닉네임 변경 API

[FEAT]닉네임 변경 API

---

frontend/src/pages/my-page.tsx

이슈번호
resolved: #175 
작업내용
마이페이지 닉네임 수정 기능

[FEAT] 마이페이지 닉네임 변경 기능

---

frontend/src/pages/notifications.tsx

이슈번호
resolved: #177 
작업내용
알림페이지 고구마 링크 기능

[FEAT] 알림페이지 고구마 링크 기능

---

frontend/src/pages/ask-success.tsx
frontend/src/pages/ask.tsx
frontend/src/routers/common-router.tsx

- Ask page post api 적용
- 상단 헤더 수정
- #56

[FEAT] Ask page POST

---

frontend/package-lock.json
frontend/package.json
frontend/public/index.html
frontend/src/pages/home.tsx
frontend/yarn.lock

이슈번호
resolved: #180 
작업내용
메인페이지 슬라이더 기능

[FEAT] 메인페이지 좌우 슬라이더 이벤트

---

backend/selection/src/main/java/com/selection/controller/ArticleController.java
backend/selection/src/main/java/com/selection/domain/article/ArticleRepository.java
backend/selection/src/main/java/com/selection/domain/article/ArticleService.java
backend/selection/src/main/java/com/selection/domain/user/UserService.java
backend/selection/src/main/java/com/selection/dto/article/ArticleSearchResponse.java

**Subject**
- 게시글 검색 API
**Detail**
- 게시글 검색 API ( 제목 또는 내용에 키워드 검사 )

[FEAT] 게시글 검색 API

---

backend/selection/src/main/java/com/selection/domain/article/Gogumas.java

**Where**
- 고구마 삭제 코드
**Bug detail**
- 삭제할 고구마에 대해서만 검증이 이루어져야하나, 모든 고구마에 검증이 이루어짐
**Fix plan**
- 검증 부분 완화

[FIX] 고구마 삭제부분 버그 수정

---

frontend/src/interface/IData.tsx
frontend/src/pages/ask.tsx
frontend/src/pages/home.tsx

- feat: Apply API on main page cards
- fix: Reset clickable card area
일단 하나씩 하는대로 푸시하려고 합니다~

[FEAT] Main page Card API

---

frontend/src/pages/search.tsx

이슈번호
resolved: #186 
작업내용
검색 페이지 api 연동

[FEAT] 검색 페이지 api 연동

---

frontend/src/pages/notifications.tsx

이슈번호
resolved: #188 
작업내용
알림페이지 알림 없을시 문구 추가

[FEAT] 알림페이지 알림없을시 문구

---

frontend/src/components/main-header.tsx

[FEAT] Add main header divider

---

backend/selection/src/main/java/com/selection/dto/OAuthAttributes.java

**Subject**
- 소셜 로그인 이름이 없을 경우 예외 처리
**Detail**
- 소셜 로그인 이름을 초기 닉네임으로 사용하나, 이름을 받아오지 못할 경우

[REFACTOR] 소셜 로그인 이름이 없을 경우 예외 처리

---

frontend/src/components/sidebar.tsx
frontend/src/styles/img/icon_alarm_0.svg

fix: sidebar CSS

---

frontend/src/constants.ts

fix: fronturl fix

---

frontend/src/components/content-header.tsx
frontend/src/pages/goguma-gogumas.tsx
frontend/src/pages/goguma.tsx

fix: fix redirect

---

frontend/src/pages/goguma.tsx

fix: goguma delete error

---

frontend/src/pages/goguma.tsx

fix: basket error

---

frontend/src/App.tsx
frontend/src/components/content-header.tsx
frontend/src/pages/goguma-basket.tsx
frontend/src/pages/goguma-gogumas.tsx
frontend/src/pages/goguma-list-me.tsx
frontend/src/pages/goguma.tsx
frontend/src/pages/login.tsx
frontend/src/pages/my-page.tsx
frontend/src/pages/notifications.tsx
frontend/src/pages/oauth2-redirect.tsx
frontend/src/routers/common-router.tsx

fix: link error

---

frontend/src/pages/goguma-list-me.tsx
frontend/src/pages/notifications.tsx

내가 쓴 페이지에서 token확인이 정상적으로 수행되지 않던 에러

fix: List Page Token Error

---

frontend/src/pages/home.tsx
frontend/src/routers/common-router.tsx

feat: ask button hidden visible

---

frontend/src/pages/notifications.tsx

fix: notification error

---

frontend/src/pages/goguma-info.tsx

refactor: update information
